# Generated by Django 5.2.3 on 2025-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_dailyxpclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyxpclaim',
            name='xp_awarded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
