services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 syntax.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A syntax worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A syntax beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
