# Generated by Django 5.2.3 on 2025-07-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_level_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_solved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
