# Generated by Django 5.2.3 on 2025-06-27 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('test_cases', models.JSONField(default=list)),
                ('time_limit', models.IntegerField(default=2)),
                ('tags', models.JSONField(default=list)),
                ('hints', models.JSONField(default=list)),
                ('required_skills', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('function_signature', models.TextField(blank=True, null=True)),
                ('languages', models.JSONField(default=list)),
                ('initial_code', models.JSONField(default=dict)),
                ('solution_code', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('xp_reward', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
