# Generated by Django 5.2.3 on 2025-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
